-- The central work item: the backlog row everything else hangs off of.
-- Status tracks lifecycle; tags[] track permission (governance). The two
-- CHECK constraints below encode the heart of the governance model.

CREATE TABLE work_items (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status        text NOT NULL DEFAULT 'new',
  priority      integer NOT NULL DEFAULT 1,
  source        text NOT NULL DEFAULT '',
  category      text NOT NULL DEFAULT '',
  title         text NOT NULL,
  body          text NOT NULL DEFAULT '',
  operator_note text NOT NULL DEFAULT '',
  work_type     text REFERENCES work_types (work_type),
  tags          text[] NOT NULL DEFAULT '{}',
  chat_channel_id  text,
  chat_message_id  text,
  chat_thread_id   text,
  chat_reply_to_id text,
  metadata      jsonb NOT NULL DEFAULT '{}',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_items_status_check
    CHECK (status IN ('new', 'triaged', 'blocked', 'done', 'ignored')),
  CONSTRAINT work_items_priority_check
    CHECK (priority >= 0),
  -- A blocked item can never also be autonomous_safe (demotion on block).
  CONSTRAINT work_items_blocked_not_autonomous_safe_check
    CHECK (status <> 'blocked' OR NOT (tags @> ARRAY['autonomous_safe'])),
  -- A dependency-blocked item cannot sit in an open lifecycle status.
  CONSTRAINT work_items_dependency_blocked_status_check
    CHECK (status NOT IN ('new', 'triaged') OR NOT (tags @> ARRAY['blocked_on_dependency']))
);

CREATE INDEX work_items_status_idx ON work_items (status);
CREATE INDEX work_items_priority_idx ON work_items (priority DESC);
CREATE INDEX work_items_category_idx ON work_items (category);
CREATE INDEX work_items_work_type_idx ON work_items (work_type);
CREATE INDEX work_items_tags_gin_idx ON work_items USING gin (tags);
