-- Satellites of work_items: candidate intake, tag/surface mappings, links,
-- machine-checkable preconditions, and worker claims/leases.

-- Candidate-first doctrine: agents file candidates; humans promote to work items.
CREATE TABLE work_item_candidates (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status            text NOT NULL DEFAULT 'pending',
  filter_reason     text NOT NULL DEFAULT '',
  proposed_title    text NOT NULL,
  proposed_body     text NOT NULL DEFAULT '',
  proposed_category text,
  proposed_priority integer NOT NULL DEFAULT 1,
  source            text NOT NULL DEFAULT '',
  external_ref      text,
  source_content    text NOT NULL DEFAULT '',
  chat_channel_id   text,
  chat_thread_id    text,
  metadata          jsonb NOT NULL DEFAULT '{}',
  captured_at       timestamptz NOT NULL DEFAULT now(),
  reviewed_at       timestamptz,
  created_work_item_id bigint REFERENCES work_items (id) ON DELETE SET NULL,
  CONSTRAINT work_item_candidates_status_check
    CHECK (status IN ('pending', 'approved', 'rejected', 'edited')),
  -- Dedup key for automated intake. NULL external_ref rows (manual candidates)
  -- are not deduped, since NULLs are distinct in a UNIQUE constraint.
  CONSTRAINT work_item_candidates_source_ref_key UNIQUE (source, external_ref)
);

-- Tag assignments with provenance. Mirror of work_items.tags[] for audit/history.
CREATE TABLE work_item_tags (
  work_item_id bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  tag          text NOT NULL REFERENCES governance_tags (tag),
  applied_by   text NOT NULL DEFAULT '',
  applied_at   timestamptz NOT NULL DEFAULT now(),
  source       text NOT NULL DEFAULT '',
  note         text NOT NULL DEFAULT '',
  PRIMARY KEY (work_item_id, tag)
);

CREATE TABLE work_item_surfaces (
  work_item_id bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  surface      text NOT NULL REFERENCES surfaces (surface),
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (work_item_id, surface)
);

-- Parent/child and blocker relationships between work items.
CREATE TABLE work_item_links (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_work_item_id bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  child_work_item_id  bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  link_kind           text NOT NULL DEFAULT 'blocked_by',
  created_by          text NOT NULL DEFAULT 'system',
  metadata            jsonb NOT NULL DEFAULT '{}',
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT work_item_links_link_kind_check
    CHECK (link_kind IN ('blocked_by', 'followup', 'related', 'supersedes', 'decision_for')),
  CONSTRAINT work_item_links_no_self_link
    CHECK (parent_work_item_id <> child_work_item_id),
  CONSTRAINT work_item_links_unique
    UNIQUE (parent_work_item_id, child_work_item_id, link_kind)
);

-- Machine-checkable preconditions that re-arm a blocked item when satisfied.
CREATE TABLE preconditions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  work_item_id bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  kind         text NOT NULL,
  target       text NOT NULL,
  satisfied_at timestamptz,
  metadata     jsonb NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT preconditions_kind_check
    CHECK (kind IN ('db_object', 'migration', 'file'))
);

CREATE INDEX preconditions_work_item_idx ON preconditions (work_item_id);

-- One active lease per work item; prevents two workers colliding.
CREATE TABLE claims (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  work_item_id     bigint NOT NULL REFERENCES work_items (id) ON DELETE CASCADE,
  claim_status     text NOT NULL DEFAULT 'active',
  runner_id        text NOT NULL,
  runner_kind      text NOT NULL DEFAULT 'manual',
  session_ref      text,
  repo_path        text,
  branch_name      text,
  worktree_path    text,
  claimed_at       timestamptz NOT NULL DEFAULT now(),
  heartbeat_at     timestamptz NOT NULL DEFAULT now(),
  lease_expires_at timestamptz NOT NULL DEFAULT (now() + interval '2 hours'),
  released_at      timestamptz,
  outcome          text,
  metadata         jsonb NOT NULL DEFAULT '{}',
  evidence         jsonb NOT NULL DEFAULT '{}',
  CONSTRAINT claims_status_check
    CHECK (claim_status IN ('active', 'released', 'completed', 'blocked', 'expired', 'abandoned', 'failed')),
  CONSTRAINT claims_runner_kind_check
    CHECK (runner_kind IN ('manual', 'agent', 'worker', 'automation', 'other'))
);

CREATE INDEX claims_work_item_idx ON claims (work_item_id);
-- At most one active claim per work item.
CREATE UNIQUE INDEX claims_one_active_per_item
  ON claims (work_item_id) WHERE claim_status = 'active';
